### ISSUE TITLE
Recovery beep

### ISSUE THREAD

**Issue by hachibu** [mgeraci/hangboard-timer#11]
I was hangboarding today and I think it would be cool to know audibly when the recovery timer starts so I don't have to look at my screen.

One idea I had was a special beep for recovery. Maybe 2 beeps for recovery and 3 beeps for complete.

I don't know if that's the best. What do you think?

**Comment by mgeraci** [comment]
Yeah, I get you — there used to be a special beep when the program finished, but since you added recovery as a new state, it doesn't think it's finished up until recovery is done as well. To simplify things, I'll play the "end beep" (three sets of three beeps) at the start and end of the recovery period.

**Comment by hachibu** [comment]
Ah, ok. I like that idea.
